openapi: 3.0.0
info:
  title: Orders API
  version: 1.0.0
paths:
  /api/orders:
    get:
      summary: Get all orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of orders
    post:
      summary: Create new order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
  /api/orders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get order by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Order found
    put:
      summary: Update order
      security:
        - bearerAuth: []
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        '200':
          description: "Order updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        '404':
          description: "Order not found"
        '400':
          description: "Validation error"
    delete:
      summary: Delete order
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Order deleted
    patch:
      summary: Partially update order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        '200':
          description: Order partially updated
components:
  schemas:
    Order:
      type: object
      properties:
        OrderNo:
          type: number
        OrderDate:
          type: string
          format: date
        CustNo:
          type: number
        ProductName:
          type: string
        ProductQuantity:
          type: integer
        ProductPrice:
          type: number
          format: float
        TotalPrice:
          type: number
          format: float
        ModeOfPayment:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
